// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pixkey.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PixKeyRegistration struct {
	Kind                 string   `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	AccountId            string   `protobuf:"bytes,3,opt,name=accountId,proto3" json:"accountId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PixKeyRegistration) Reset()         { *m = PixKeyRegistration{} }
func (m *PixKeyRegistration) String() string { return proto.CompactTextString(m) }
func (*PixKeyRegistration) ProtoMessage()    {}
func (*PixKeyRegistration) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c629aa9982df412, []int{0}
}

func (m *PixKeyRegistration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PixKeyRegistration.Unmarshal(m, b)
}
func (m *PixKeyRegistration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PixKeyRegistration.Marshal(b, m, deterministic)
}
func (m *PixKeyRegistration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PixKeyRegistration.Merge(m, src)
}
func (m *PixKeyRegistration) XXX_Size() int {
	return xxx_messageInfo_PixKeyRegistration.Size(m)
}
func (m *PixKeyRegistration) XXX_DiscardUnknown() {
	xxx_messageInfo_PixKeyRegistration.DiscardUnknown(m)
}

var xxx_messageInfo_PixKeyRegistration proto.InternalMessageInfo

func (m *PixKeyRegistration) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *PixKeyRegistration) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PixKeyRegistration) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type PixKey struct {
	Kind                 string   `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PixKey) Reset()         { *m = PixKey{} }
func (m *PixKey) String() string { return proto.CompactTextString(m) }
func (*PixKey) ProtoMessage()    {}
func (*PixKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c629aa9982df412, []int{1}
}

func (m *PixKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PixKey.Unmarshal(m, b)
}
func (m *PixKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PixKey.Marshal(b, m, deterministic)
}
func (m *PixKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PixKey.Merge(m, src)
}
func (m *PixKey) XXX_Size() int {
	return xxx_messageInfo_PixKey.Size(m)
}
func (m *PixKey) XXX_DiscardUnknown() {
	xxx_messageInfo_PixKey.DiscardUnknown(m)
}

var xxx_messageInfo_PixKey proto.InternalMessageInfo

func (m *PixKey) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *PixKey) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type Account struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	AccountNumber        string   `protobuf:"bytes,2,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	BankId               string   `protobuf:"bytes,3,opt,name=bankId,proto3" json:"bankId,omitempty"`
	BankName             string   `protobuf:"bytes,4,opt,name=bankName,proto3" json:"bankName,omitempty"`
	OwnerName            string   `protobuf:"bytes,5,opt,name=OwnerName,proto3" json:"OwnerName,omitempty"`
	CreatedAt            string   `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c629aa9982df412, []int{2}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *Account) GetAccountNumber() string {
	if m != nil {
		return m.AccountNumber
	}
	return ""
}

func (m *Account) GetBankId() string {
	if m != nil {
		return m.BankId
	}
	return ""
}

func (m *Account) GetBankName() string {
	if m != nil {
		return m.BankName
	}
	return ""
}

func (m *Account) GetOwnerName() string {
	if m != nil {
		return m.OwnerName
	}
	return ""
}

func (m *Account) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type PixKeyInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind                 string   `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Account              *Account `protobuf:"bytes,4,opt,name=account,proto3" json:"account,omitempty"`
	CraetedAt            string   `protobuf:"bytes,5,opt,name=craetedAt,proto3" json:"craetedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PixKeyInfo) Reset()         { *m = PixKeyInfo{} }
func (m *PixKeyInfo) String() string { return proto.CompactTextString(m) }
func (*PixKeyInfo) ProtoMessage()    {}
func (*PixKeyInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c629aa9982df412, []int{3}
}

func (m *PixKeyInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PixKeyInfo.Unmarshal(m, b)
}
func (m *PixKeyInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PixKeyInfo.Marshal(b, m, deterministic)
}
func (m *PixKeyInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PixKeyInfo.Merge(m, src)
}
func (m *PixKeyInfo) XXX_Size() int {
	return xxx_messageInfo_PixKeyInfo.Size(m)
}
func (m *PixKeyInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PixKeyInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PixKeyInfo proto.InternalMessageInfo

func (m *PixKeyInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PixKeyInfo) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *PixKeyInfo) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PixKeyInfo) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *PixKeyInfo) GetCraetedAt() string {
	if m != nil {
		return m.CraetedAt
	}
	return ""
}

type PixKeyCreatedResult struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PixKeyCreatedResult) Reset()         { *m = PixKeyCreatedResult{} }
func (m *PixKeyCreatedResult) String() string { return proto.CompactTextString(m) }
func (*PixKeyCreatedResult) ProtoMessage()    {}
func (*PixKeyCreatedResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c629aa9982df412, []int{4}
}

func (m *PixKeyCreatedResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PixKeyCreatedResult.Unmarshal(m, b)
}
func (m *PixKeyCreatedResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PixKeyCreatedResult.Marshal(b, m, deterministic)
}
func (m *PixKeyCreatedResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PixKeyCreatedResult.Merge(m, src)
}
func (m *PixKeyCreatedResult) XXX_Size() int {
	return xxx_messageInfo_PixKeyCreatedResult.Size(m)
}
func (m *PixKeyCreatedResult) XXX_DiscardUnknown() {
	xxx_messageInfo_PixKeyCreatedResult.DiscardUnknown(m)
}

var xxx_messageInfo_PixKeyCreatedResult proto.InternalMessageInfo

func (m *PixKeyCreatedResult) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PixKeyCreatedResult) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *PixKeyCreatedResult) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*PixKeyRegistration)(nil), "github.com.JoaoRafa19.codepix.PixKeyRegistration")
	proto.RegisterType((*PixKey)(nil), "github.com.JoaoRafa19.codepix.PixKey")
	proto.RegisterType((*Account)(nil), "github.com.JoaoRafa19.codepix.Account")
	proto.RegisterType((*PixKeyInfo)(nil), "github.com.JoaoRafa19.codepix.PixKeyInfo")
	proto.RegisterType((*PixKeyCreatedResult)(nil), "github.com.JoaoRafa19.codepix.PixKeyCreatedResult")
}

func init() {
	proto.RegisterFile("pixkey.proto", fileDescriptor_9c629aa9982df412)
}

var fileDescriptor_9c629aa9982df412 = []byte{
	// 402 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xd1, 0xae, 0xd2, 0x40,
	0x10, 0x86, 0x69, 0x81, 0x22, 0xa3, 0xa2, 0xae, 0x86, 0x34, 0x44, 0x13, 0xd3, 0xa8, 0xd1, 0x9b,
	0x35, 0xe0, 0x95, 0xf1, 0x46, 0x34, 0x31, 0x41, 0x13, 0x34, 0xe5, 0xc6, 0x70, 0xb7, 0x6d, 0x07,
	0xdc, 0x14, 0xba, 0xcd, 0x76, 0xab, 0xf4, 0x75, 0x7c, 0x0f, 0x9f, 0xc6, 0x17, 0x39, 0xe9, 0xee,
	0x52, 0xc2, 0x21, 0x39, 0xa7, 0x77, 0xfb, 0xff, 0xd3, 0x99, 0xfd, 0x66, 0x76, 0x0a, 0xf7, 0x72,
	0x7e, 0x48, 0xb1, 0xa2, 0xb9, 0x14, 0x4a, 0x90, 0x67, 0x5b, 0xae, 0x7e, 0x95, 0x11, 0x8d, 0xc5,
	0x9e, 0x7e, 0x15, 0x4c, 0x84, 0x6c, 0xc3, 0xa6, 0xef, 0x69, 0x2c, 0x12, 0xcc, 0xf9, 0x21, 0xf8,
	0x09, 0xe4, 0x07, 0x3f, 0x7c, 0xc3, 0x2a, 0xc4, 0x2d, 0x2f, 0x94, 0x64, 0x8a, 0x8b, 0x8c, 0x10,
	0xe8, 0xa5, 0x3c, 0x4b, 0x7c, 0xe7, 0xb9, 0xf3, 0x7a, 0x18, 0xea, 0x33, 0x79, 0x08, 0xdd, 0x14,
	0x2b, 0xdf, 0xd5, 0x56, 0x7d, 0x24, 0x4f, 0x61, 0xc8, 0xe2, 0x58, 0x94, 0x99, 0x5a, 0x24, 0x7e,
	0x57, 0xfb, 0x27, 0x23, 0xa0, 0xe0, 0x99, 0xca, 0xed, 0xaa, 0x05, 0xff, 0x1c, 0x18, 0xcc, 0x4d,
	0xf6, 0x79, 0x65, 0xe7, 0x5a, 0x65, 0xf2, 0x02, 0xee, 0x5b, 0xb1, 0x2c, 0xf7, 0x11, 0x4a, 0x5b,
	0xe5, 0xdc, 0x24, 0x63, 0xf0, 0x22, 0x96, 0xa5, 0x0d, 0x9a, 0x55, 0x64, 0x02, 0x77, 0xea, 0xd3,
	0x92, 0xed, 0xd1, 0xef, 0xe9, 0x48, 0xa3, 0xeb, 0x7b, 0xbf, 0xff, 0xc9, 0x50, 0xea, 0x60, 0xdf,
	0xdc, 0xdb, 0x18, 0x75, 0x34, 0x96, 0xc8, 0x14, 0x26, 0x73, 0xe5, 0x7b, 0x26, 0xda, 0x18, 0xc1,
	0x5f, 0x07, 0xc0, 0x34, 0xbc, 0xc8, 0x36, 0x82, 0x8c, 0xc0, 0xe5, 0x47, 0x76, 0x97, 0x27, 0xcd,
	0x10, 0xdc, 0xcb, 0x21, 0x74, 0x4f, 0x23, 0xfd, 0x08, 0x03, 0xdb, 0x85, 0x66, 0xbb, 0x3b, 0x7b,
	0x45, 0x6f, 0x7c, 0x3f, 0x6a, 0x27, 0x16, 0x1e, 0xd3, 0x0c, 0x24, 0x43, 0x03, 0xd9, 0x3f, 0x42,
	0x5a, 0x23, 0x58, 0xc1, 0x63, 0xc3, 0xf8, 0xd9, 0x70, 0x87, 0x58, 0x94, 0x3b, 0x75, 0x01, 0x3b,
	0x06, 0xaf, 0x50, 0x4c, 0x95, 0x85, 0xc5, 0xb5, 0x8a, 0x3c, 0x81, 0x3e, 0x4a, 0x29, 0xa4, 0x45,
	0x36, 0x62, 0xf6, 0xdf, 0x74, 0xbe, 0x42, 0xf9, 0x9b, 0xc7, 0x48, 0x2a, 0x18, 0x99, 0x65, 0x42,
	0x69, 0x17, 0x60, 0x7a, 0x4b, 0x13, 0x97, 0x1b, 0x38, 0x99, 0xb5, 0x4a, 0x39, 0xeb, 0x22, 0xe8,
	0x90, 0x35, 0xf4, 0xbe, 0xd4, 0x83, 0x7d, 0xd9, 0x2a, 0x7b, 0xf2, 0xa6, 0xd5, 0x67, 0xf5, 0x73,
	0x06, 0x9d, 0x4f, 0x8f, 0xd6, 0x0f, 0xe8, 0x5b, 0xfd, 0x4f, 0x6d, 0xf8, 0x0e, 0x8b, 0x0f, 0x79,
	0x14, 0x79, 0x5a, 0xbe, 0xbb, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x62, 0x81, 0x5c, 0x40, 0x72, 0x03,
	0x00, 0x00,
}
